[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Chain configurations 
[rpc_endpoints]
# Local development
anvil = "http://localhost:8545"
# Testnets
sepolia = "${SEPOLIA_RPC_URL}"
# goerli = "${GOERLI_RPC_URL}"
# Mainnets
# mainnet = "${MAINNET_RPC_URL}"
# polygon = "${POLYGON_RPC_URL}"
# arbitrum = "${ARBITRUM_RPC_URL}"
# optimism = "${OPTIMISM_RPC_URL}"

# Etherscan API keys for verification
[etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# polygon = { key = "${POLYGONSCAN_API_KEY}" }
# arbitrum = { key = "${ARBISCAN_API_KEY}" }
# optimism = { key = "${OPTIMISM_API_KEY}" }

